application.register('spreadsheet--cell', CellController)
application.register('spreadsheet--header', HeaderController)
application.register('spreadsheet--row', RowController)
application.register('spreadsheet--row-group', RowGroupController)
application.register('spreadsheet--search', SearchController)
application.register('spreadsheet--sheet', SheetController)
application.register('spreadsheet--sortable', SortableController)
